name: uncertainty_quantification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - gpy==1.13.1
  - optuna==4.0.0
  - torch==2.3.1+cu121
  - rdkit==2023.9.4
  - scikit-learn==1.5.0
  - pandas==2.2.2
  - scikit-learn==1.5.0
  - numpy=1.26.4
  - ngboost